apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-restart-notifier-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["monitoring.alhazenlabs.com"]
  resources: ["podnotifrestarts"]
  verbs: ["*"]